server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:h2:file:~/customer;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        showSql: false

endpoints:
  actuator:
    enabled: true
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:Alt3n@alten-challenge-registry.herokuapp.com:}/eureka/
security:
  user:
    password: ${eureka.password}
endpoints:
  actuator:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME:alten-challenge-customer.herokuapp.com}
    nonSecurePort: 80
  password: ${USER_PASSWORD:Custom3r}