server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    customers:
      path: /customer/**
      serviceId: customer
      strip-prefix: false
    vehicles:
      path: /vehicle/**
      serviceId: vehicle
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/